//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatisProgrami1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBarkodEntities : DbContext
    {
        public DbBarkodEntities()
            : base("name=DbBarkodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barkod> Barkods { get; set; }
        public virtual DbSet<HizliUrun> HizliUruns { get; set; }
        public virtual DbSet<Islem> Islems { get; set; }
        public virtual DbSet<IslemOzet> IslemOzets { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Sabit> Sabits { get; set; }
        public virtual DbSet<Satis> Satiss { get; set; }
        public virtual DbSet<StokHareket> StokHarekets { get; set; }
        public virtual DbSet<Terazi> Terazis { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<UrunGrup> UrunGrups { get; set; }
    }
}
